### ISSUE TITLE
[Bug] 미니게임 클리어 후 다시 미니게임 하면 오류 발생

### ISSUE THREAD

**Issue by Hoon9901** [jadru/Casino-J#5]
오류 내용 
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Timer already cancelled.
    at java.base/java.util.Timer.sched(Timer.java:398)
    at java.base/java.util.Timer.schedule(Timer.java:249)
    at screen.ui.GameSelectScreen$2.actionPerformed(GameSelectScreen.java:54)
    at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
    at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
    at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
    at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)

**Comment by Hoon9901** [comment]
오류 발생 경위
미니게임 한판 클리어하고 다시 게임하게 되면 위 오류가 발생하는데.
Timer already cancelled. 라 뜨는거 보니 미니게임 쓰레드 초기화안해서 발생하는 거같습니다.
